name: tinkoff_sdk
description: Flutter TinkoffSDK plugin
version: 0.4.3
homepage: "https://github.com/Progressive-Mobile/tinkoff_sdk"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tech.pmobi.tinkoff_sdk
        pluginClass: TinkoffSdkPlugin
      ios:
        pluginClass: TinkoffSdkPlugin
